name: CI Pipeline

on:
  push:
    branches:
      - Workflow
  pull_request:
    branches:
      - Workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Jest tests
        run: npm run test-jest

      - name: Build project
        run: npm run build

  cypress:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start server and wait for it to be ready
        run: |
          npm start &  # Start the server in the background
          npx wait-on http://localhost:8080  # Wait for the server to be ready

      - name: Run Cypress tests
        run: npx cypress run  # Run Cypress in headless mode instead of opening the GUI
